import type { Property } from './types';

export const mockProperties: Property[] = [
  {
    _id: '1',
    title: 'Monoambiente en venta – Centeno 445',
    slug: { current: 'monoambiente-centeno-445' },
    operation: 'venta',
    propertyType: 'departamento',
    price: 0,
    priceOnRequest: true,
    currency: 'USD',
    address: 'Centeno 445, 3° piso frente',
    city: 'Santa Rosa',
    province: 'La Pampa',
    description:
      'Excelente oportunidad de inversión. Departamento monoambiente en tercer piso contra frente, acceso por escaleras. Amoblado. Ubicación privilegiada a metros de Av. San Martín Oeste y a solo 6 cuadras de la plaza. Expensas bajas, ideal para quienes buscan practicidad y economía. Un espacio funcional, luminoso y con la comodidad de estar cerca de todo lo que necesitás.',
    features: {
      bedrooms: 1,
      bathrooms: 1,
      amenities: ['Amoblado', 'Expensas bajas', 'A metros de Av. San Martín', 'Zona céntrica'],
    },
    images: [
      { asset: { url: '/propiedades/prop-1/01.jpg' }, alt: 'Monoambiente Centeno 445' },
      { asset: { url: '/propiedades/prop-1/02.jpg' } },
      { asset: { url: '/propiedades/prop-1/03.jpg' } },
      { asset: { url: '/propiedades/prop-1/04.jpg' } },
      { asset: { url: '/propiedades/prop-1/05.jpg' } },
      { asset: { url: '/propiedades/prop-1/06.jpg' } },
      { asset: { url: '/propiedades/prop-1/07.jpg' } },
      { asset: { url: '/propiedades/prop-1/08.jpg' } },
      { asset: { url: '/propiedades/prop-1/09.jpg' } },
      { asset: { url: '/propiedades/prop-1/10.jpg' } },
      { asset: { url: '/propiedades/prop-1/11.jpg' } },
      { asset: { url: '/propiedades/prop-1/12.jpg' } },
    ],
    isFeatured: true,
    status: 'disponible',
    publishedAt: '2026-05-29',
  },
  {
    _id: '2',
    title: 'Terreno en Villa Martita – Camarero',
    slug: { current: 'terreno-villa-martita-camarero' },
    operation: 'venta',
    propertyType: 'terreno',
    price: 0,
    priceOnRequest: true,
    currency: 'USD',
    address: 'Calle Camarero, Villa Martita',
    city: 'Santa Rosa',
    province: 'La Pampa',
    description:
      'Terreno amplio en una de las zonas más lindas de la ciudad. Ideal para proyectar la casa de tus sueños o una inversión segura. La amplitud de sus medidas lo convierte en una oportunidad única. En Villa Martita, rodeado de un entorno tranquilo y agradable — la combinación perfecta de espacio, servicios y ubicación.',
    features: {
      totalArea: 1200,
      amenities: ['30 m de frente', '40 m de fondo', 'Luz eléctrica', 'Gas natural'],
    },
    images: [
      { asset: { url: '/propiedades/prop-2/01.jpg' }, alt: 'Terreno Villa Martita' },
      { asset: { url: '/propiedades/prop-2/02.jpg' } },
    ],
    isFeatured: false,
    status: 'disponible',
    publishedAt: '2026-05-29',
  },
  {
    _id: '3',
    title: 'Galpón + Lote en venta – Ataliva Roca',
    slug: { current: 'galpon-lote-ataliva-roca' },
    operation: 'venta',
    propertyType: 'local',
    price: 0,
    priceOnRequest: true,
    currency: 'USD',
    address: 'Ataliva Roca',
    city: 'Ataliva Roca',
    province: 'La Pampa',
    description:
      'Ideal para depósito, taller o emprendimiento. Lote de 15,70 × 50 m con galpón de 67 m² de construcción de ladrillo, piso de cemento alisado y techo metálico. Portón corredizo para carga y descarga. Excelente altura interior, estructura de hierro firme y mucho espacio libre para proyectar. Luz trifásica, agua. Gas disponible en la vereda.',
    features: {
      coveredArea: 67,
      totalArea: 785,
      amenities: ['Galpón de ladrillo', 'Portón corredizo', 'Luz trifásica', 'Agua corriente', 'Gas en vereda', 'Techo metálico'],
    },
    images: [
      { asset: { url: '/propiedades/prop-3/01.jpg' }, alt: 'Galpón Ataliva Roca' },
      { asset: { url: '/propiedades/prop-3/02.jpg' } },
    ],
    isFeatured: false,
    status: 'disponible',
    publishedAt: '2026-05-29',
  },
  {
    _id: '4',
    title: 'Terrenos en venta – Toay',
    slug: { current: 'terrenos-toay-uspallata-bolivar' },
    operation: 'venta',
    propertyType: 'terreno',
    price: 12500,
    currency: 'USD',
    address: 'Uspallata esq. Bolívar',
    city: 'Toay',
    province: 'La Pampa',
    description:
      'Oportunidad de inversión accesible en Toay. Superficie de 312,5 m² (12,50 × 25 m). Servicio de luz. Financiación disponible. Solo quedan 3 lotes disponibles — ¡no esperes! Consultá por precio y condiciones de pago.',
    features: {
      totalArea: 313,
      amenities: ['Luz eléctrica', 'Financiación disponible', '12,50 × 25 m'],
    },
    images: [
      { asset: { url: '/propiedades/prop-4/01.jpg' }, alt: 'Terreno Toay' },
      { asset: { url: '/propiedades/prop-4/02.jpg' } },
    ],
    isFeatured: true,
    status: 'disponible',
    publishedAt: '2026-05-29',
  },
  {
    _id: '5',
    title: 'Depósito en venta – 10 × 50',
    slug: { current: 'deposito-venta-10x50' },
    operation: 'venta',
    propertyType: 'local',
    price: 0,
    priceOnRequest: true,
    currency: 'USD',
    address: 'Santa Rosa',
    city: 'Santa Rosa',
    province: 'La Pampa',
    description:
      'Depósito en venta de 10 × 50 m (500 m²). Ideal para actividad industrial, logística o almacenamiento. Consultá por precio y más detalles.',
    features: {
      coveredArea: 500,
      amenities: ['500 m² cubiertos', '10 m de frente', '50 m de fondo'],
    },
    images: [
      { asset: { url: '/propiedades/prop-5/01.jpg' }, alt: 'Depósito en venta' },
      { asset: { url: '/propiedades/prop-5/02.jpg' } },
      { asset: { url: '/propiedades/prop-5/03.jpg' } },
      { asset: { url: '/propiedades/prop-5/04.jpg' } },
    ],
    isFeatured: false,
    status: 'disponible',
    publishedAt: '2026-05-29',
  },
  {
    _id: '6',
    title: 'Casa en venta – Calle Perdiz esq. Liebre',
    slug: { current: 'casa-calle-perdiz-liebre' },
    operation: 'venta',
    propertyType: 'casa',
    price: 0,
    priceOnRequest: true,
    currency: 'USD',
    address: 'Calle Perdiz esq. Liebre',
    city: 'Santa Rosa',
    province: 'La Pampa',
    description:
      'Casa en venta con excelentes comodidades. Living comedor con aire acondicionado frío/calor, calefactor 4.000 calorías y estufa hogar a leña. Dormitorio con aire acondicionado frío. Dormitorio principal en suite con aire frío/calor. Loza radiante eléctrica sectorizada (3 sectores: estudio, dormitorio, dormitorio en suite y baño). Termotanque a gas.',
    features: {
      bedrooms: 2,
      bathrooms: 2,
      amenities: [
        'Aire acondicionado (3 unidades)',
        'Calefactor 4000 cal',
        'Estufa hogar a leña',
        'Loza radiante eléctrica (3 sectores)',
        'Dormitorio principal en suite',
        'Termotanque a gas',
      ],
    },
    images: [
      { asset: { url: '/propiedades/prop-6/01.jpg' }, alt: 'Casa Calle Perdiz' },
      { asset: { url: '/propiedades/prop-6/02.jpg' } },
      { asset: { url: '/propiedades/prop-6/03.jpg' } },
      { asset: { url: '/propiedades/prop-6/04.jpg' } },
      { asset: { url: '/propiedades/prop-6/05.jpg' } },
      { asset: { url: '/propiedades/prop-6/06.jpg' } },
      { asset: { url: '/propiedades/prop-6/07.jpg' } },
      { asset: { url: '/propiedades/prop-6/08.jpg' } },
      { asset: { url: '/propiedades/prop-6/09.jpg' } },
      { asset: { url: '/propiedades/prop-6/10.jpg' } },
      { asset: { url: '/propiedades/prop-6/11.jpg' } },
      { asset: { url: '/propiedades/prop-6/12.jpg' } },
      { asset: { url: '/propiedades/prop-6/13.jpg' } },
      { asset: { url: '/propiedades/prop-6/14.jpg' } },
      { asset: { url: '/propiedades/prop-6/15.jpg' } },
      { asset: { url: '/propiedades/prop-6/16.jpg' } },
      { asset: { url: '/propiedades/prop-6/17.jpg' } },
      { asset: { url: '/propiedades/prop-6/18.jpg' } },
      { asset: { url: '/propiedades/prop-6/19.jpg' } },
      { asset: { url: '/propiedades/prop-6/20.jpg' } },
      { asset: { url: '/propiedades/prop-6/21.jpg' } },
      { asset: { url: '/propiedades/prop-6/22.jpg' } },
      { asset: { url: '/propiedades/prop-6/23.jpg' } },
    ],
    isFeatured: true,
    status: 'disponible',
    publishedAt: '2026-05-29',
  },
  {
    _id: '7',
    title: 'Terrenos en venta – Ataliva Roca (Calle Córdoba)',
    slug: { current: 'terrenos-ataliva-roca-cordoba' },
    operation: 'venta',
    propertyType: 'terreno',
    price: 0,
    priceOnRequest: true,
    currency: 'USD',
    address: 'Calle Córdoba entre Rivadavia y Las Heras',
    city: 'Ataliva Roca',
    province: 'La Pampa',
    description:
      'Terrenos en venta en Ataliva Roca. Gas, agua y luz pasan por la vereda. Dos opciones disponibles: Terreno N° 25 de 15 × 35 m (525 m²) y Terreno N° 24 de 15 × 50 m (750 m²). Consultá por precio y disponibilidad.',
    features: {
      totalArea: 750,
      amenities: ['Gas en vereda', 'Agua corriente', 'Luz eléctrica', 'Opción 15×35 m o 15×50 m'],
    },
    images: [
      { asset: { url: '/propiedades/prop-7/01.jpg' }, alt: 'Terreno Ataliva Roca Córdoba' },
      { asset: { url: '/propiedades/prop-7/02.jpg' } },
      { asset: { url: '/propiedades/prop-7/03.jpg' } },
      { asset: { url: '/propiedades/prop-7/04.jpg' } },
    ],
    isFeatured: false,
    status: 'disponible',
    publishedAt: '2026-05-29',
  },
  {
    _id: '8',
    title: 'Terreno en venta – Benteveo esq. Martineta',
    slug: { current: 'terreno-benteveo-martineta' },
    operation: 'venta',
    propertyType: 'terreno',
    price: 0,
    priceOnRequest: true,
    currency: 'USD',
    address: 'Calle Benteveo esq. Martineta',
    city: 'Santa Rosa',
    province: 'La Pampa',
    description:
      'Terreno en venta en excelente ubicación. Luz y gas pasan por la vereda. Consultá por precio y medidas.',
    features: {
      amenities: ['Luz eléctrica en vereda', 'Gas en vereda'],
    },
    images: [
      { asset: { url: '/propiedades/prop-8/01.jpg' }, alt: 'Terreno Benteveo Martineta' },
      { asset: { url: '/propiedades/prop-8/02.jpg' } },
    ],
    isFeatured: false,
    status: 'disponible',
    publishedAt: '2026-05-29',
  },
  {
    _id: '9',
    title: 'Casa en Bouchard 275 – Barrio Residencial',
    slug: { current: 'casa-bouchard-275' },
    operation: 'venta',
    propertyType: 'casa',
    price: 0,
    priceOnRequest: true,
    currency: 'USD',
    address: 'Bouchard N° 275, entre Maestros Pampeanos y Pasaje Sargento Núñez',
    city: 'Santa Rosa',
    province: 'La Pampa',
    description:
      'Ubicada en uno de los barrios más buscados y lindos de la ciudad, esta propiedad es ideal para quienes buscan refaccionar y revalorizar en una zona estratégica. Cuenta con cocina con bajo mesada, living, baño principal, lavadero con baño de servicio, 3 dormitorios (uno con vestidor y baño en suite), patio con parrilla y pileta, garage y planta alta con un dormitorio adicional y terraza. Gran potencial para modernizar y adaptar a las nuevas tendencias en una ubicación que garantiza valorización.',
    features: {
      bedrooms: 4,
      bathrooms: 3,
      amenities: [
        'Patio con parrilla y pileta',
        'Garage',
        'Dormitorio en suite con vestidor',
        'Planta alta con terraza',
        'Lavadero con baño de servicio',
        'Zona residencial privilegiada',
      ],
    },
    images: [
      { asset: { url: '/propiedades/prop-9/01.jpg' }, alt: 'Casa Bouchard 275' },
      { asset: { url: '/propiedades/prop-9/02.jpg' } },
      { asset: { url: '/propiedades/prop-9/03.jpg' } },
      { asset: { url: '/propiedades/prop-9/04.jpg' } },
      { asset: { url: '/propiedades/prop-9/05.jpg' } },
    ],
    isFeatured: false,
    status: 'disponible',
    publishedAt: '2026-06-04',
  },
];
