import type { Property } from './types';

export const mockProperties: Property[] = [
  {
    _id: '1',
    title: 'Casa en Moreno al 500',
    slug: { current: 'casa-moreno-500' },
    operation: 'venta',
    propertyType: 'casa',
    price: 85000,
    currency: 'USD',
    address: 'Moreno al 500',
    city: 'Santa Rosa',
    province: 'La Pampa',
    description: 'Oportunidad única para remodelar y poner tu estilo a esta propiedad. Con excelente ubicación y gran potencial, esta casa es ideal para vivienda permanente, renta o desarrollo.\n\nLa propiedad cuenta con todos los servicios y se encuentra en una zona estratégica de Santa Rosa, con fácil acceso a comercios, escuelas y transporte público.',
    features: {
      bedrooms: 2,
      bathrooms: 1,
      coveredArea: 80,
      totalArea: 150,
      garage: true,
      garden: true,
      amenities: ['Agua corriente', 'Luz eléctrica', 'Gas natural', 'Asfalto', 'Colegio cercano'],
    },
    images: [
      { asset: { url: 'https://picsum.photos/id/164/1200/800' } },
      { asset: { url: 'https://picsum.photos/id/1016/1200/800' } },
      { asset: { url: 'https://picsum.photos/id/1040/1200/800' } },
      { asset: { url: 'https://picsum.photos/id/1043/1200/800' } },
    ],
    isFeatured: true,
    status: 'disponible',
    publishedAt: '2024-01-15',
  },
  {
    _id: '2',
    title: 'Casa en Bouchard al 200',
    slug: { current: 'casa-bouchard-200' },
    operation: 'venta',
    propertyType: 'casa',
    price: 115000,
    currency: 'USD',
    address: 'Bouchard al 200',
    city: 'Santa Rosa',
    province: 'La Pampa',
    description: 'Hermosa casa con piscina, jardín y garage para dos autos. Ideal para familia numerosa que busca comodidad y espacios verdes.\n\nUbicada en zona residencial tranquila, a pocos minutos del centro.',
    features: {
      bedrooms: 3,
      bathrooms: 2,
      coveredArea: 198,
      totalArea: 338,
      garage: true,
      pool: true,
      garden: true,
      amenities: ['Agua corriente', 'Luz eléctrica', 'Gas natural', 'Asfalto', 'Pileta'],
    },
    images: [
      { asset: { url: 'https://picsum.photos/id/1016/1200/800' } },
      { asset: { url: 'https://picsum.photos/id/164/1200/800' } },
      { asset: { url: 'https://picsum.photos/id/1060/1200/800' } },
    ],
    isFeatured: true,
    status: 'disponible',
    publishedAt: '2024-01-10',
  },
  {
    _id: '3',
    title: 'Departamento en el centro',
    slug: { current: 'departamento-centro' },
    operation: 'venta',
    propertyType: 'departamento',
    price: 75000,
    currency: 'USD',
    address: 'Marcelo T. de Alvear 446',
    city: 'Santa Rosa',
    province: 'La Pampa',
    description: 'Departamento luminoso en pleno centro, bien distribuido con todos los servicios. A metros de comercios, bancos y transporte público.',
    features: {
      bedrooms: 1,
      bathrooms: 1,
      coveredArea: 43,
      totalArea: 55,
      garage: true,
      amenities: ['Agua corriente', 'Luz eléctrica', 'Gas natural', 'Portero eléctrico'],
    },
    images: [
      { asset: { url: 'https://picsum.photos/id/1040/1200/800' } },
      { asset: { url: 'https://picsum.photos/id/1076/1200/800' } },
    ],
    isFeatured: false,
    status: 'disponible',
    publishedAt: '2024-01-05',
  },
  {
    _id: '4',
    title: 'Casa en La Cuesta del Sur',
    slug: { current: 'casa-la-cuesta' },
    operation: 'venta',
    propertyType: 'casa',
    price: 60000,
    currency: 'USD',
    address: 'La Cuesta del Sur s/n',
    city: 'Toay',
    province: 'La Pampa',
    description: 'Casa a terminar con instalación trifásica y amplio terreno de 300 m². Excelente oportunidad para quien quiera darle su impronta a la construcción.',
    features: {
      bedrooms: 2,
      bathrooms: 1,
      coveredArea: 70,
      totalArea: 300,
      garage: true,
      amenities: ['Instalación trifásica', 'Terreno amplio'],
    },
    images: [
      { asset: { url: 'https://picsum.photos/id/1060/1200/800' } },
      { asset: { url: 'https://picsum.photos/id/137/1200/800' } },
    ],
    isFeatured: false,
    status: 'disponible',
    publishedAt: '2024-01-01',
  },
  {
    _id: '5',
    title: 'PH en el centro',
    slug: { current: 'ph-centro' },
    operation: 'alquiler',
    propertyType: 'ph',
    price: 350000,
    currency: 'ARS',
    address: 'San Martín 123',
    city: 'Santa Rosa',
    province: 'La Pampa',
    description: 'PH amplia con patio privado, ideal para pareja o familia pequeña. Luminosa, bien ventilada y a metros de todo.',
    features: {
      bedrooms: 2,
      bathrooms: 1,
      coveredArea: 90,
      amenities: ['Patio privado', 'Agua corriente', 'Luz eléctrica', 'Gas natural'],
    },
    images: [
      { asset: { url: 'https://picsum.photos/id/1076/1200/800' } },
      { asset: { url: 'https://picsum.photos/id/1080/1200/800' } },
    ],
    isFeatured: false,
    status: 'disponible',
    publishedAt: '2024-01-20',
  },
  {
    _id: '6',
    title: 'Terreno en barrio privado',
    slug: { current: 'terreno-barrio-privado' },
    operation: 'venta',
    propertyType: 'terreno',
    price: 45000,
    currency: 'USD',
    address: 'Ruta 35 Km 10',
    city: 'Santa Rosa',
    province: 'La Pampa',
    description: 'Terreno de 1000 m² en barrio cerrado con seguridad 24hs. Todos los servicios en el ingreso. Escritura lista.',
    features: {
      totalArea: 1000,
      amenities: ['Seguridad 24hs', 'Luz eléctrica', 'Agua corriente', 'Calle interna asfaltada'],
    },
    images: [
      { asset: { url: 'https://picsum.photos/id/1071/1200/800' } },
    ],
    isFeatured: true,
    status: 'disponible',
    publishedAt: '2024-01-18',
  },
  {
    _id: '7',
    title: 'Departamento monoambiente',
    slug: { current: 'depto-monoambiente-urquiza' },
    operation: 'alquiler',
    propertyType: 'departamento',
    price: 180000,
    currency: 'ARS',
    address: 'Urquiza 890',
    city: 'Santa Rosa',
    province: 'La Pampa',
    description: 'Monoambiente luminoso reciclado, a metros del parque Luro. Ideal para estudiantes o personas solas.',
    features: {
      bedrooms: 1,
      bathrooms: 1,
      coveredArea: 32,
      amenities: ['Agua corriente', 'Luz eléctrica', 'Gas natural'],
    },
    images: [
      { asset: { url: 'https://picsum.photos/id/1043/1200/800' } },
    ],
    isFeatured: false,
    status: 'disponible',
    publishedAt: '2024-01-22',
  },
  {
    _id: '8',
    title: 'Chalet en zona norte',
    slug: { current: 'chalet-zona-norte' },
    operation: 'venta',
    propertyType: 'casa',
    price: 195000,
    currency: 'USD',
    address: 'Los Álamos 250',
    city: 'Santa Rosa',
    province: 'La Pampa',
    description: 'Chalet estilo americano con 4 dormitorios en suite, pileta y parque de 800 m². Cocina americana equipada, sistema de riego automático y garage para 2 autos.',
    features: {
      bedrooms: 4,
      bathrooms: 3,
      coveredArea: 260,
      totalArea: 800,
      garage: true,
      pool: true,
      garden: true,
      amenities: ['Cocina equipada', 'Riego automático', 'Pileta climatizada', 'Garage doble', 'Barbacoa'],
    },
    images: [
      { asset: { url: 'https://picsum.photos/id/137/1200/800' } },
      { asset: { url: 'https://picsum.photos/id/164/1200/800' } },
      { asset: { url: 'https://picsum.photos/id/1016/1200/800' } },
    ],
    isFeatured: true,
    status: 'disponible',
    publishedAt: '2024-01-25',
  },
  {
    _id: '9',
    title: 'Local comercial en peatonal',
    slug: { current: 'local-peatonal' },
    operation: 'venta',
    propertyType: 'local',
    price: 130000,
    currency: 'USD',
    address: 'Peatonal Rivadavia 340',
    city: 'Santa Rosa',
    province: 'La Pampa',
    description: 'Excelente local en la peatonal principal, 60 m² con vidriera, depósito y baño. La mejor ubicación comercial de Santa Rosa.',
    features: {
      coveredArea: 60,
      amenities: ['Vidriera', 'Depósito', 'Baño', 'Alarma'],
    },
    images: [
      { asset: { url: 'https://picsum.photos/id/180/1200/800' } },
    ],
    isFeatured: false,
    status: 'disponible',
    publishedAt: '2024-01-08',
  },
  {
    _id: '10',
    title: 'Departamento 2 ambientes',
    slug: { current: 'depto-2-ambientes-belgrano' },
    operation: 'alquiler',
    propertyType: 'departamento',
    price: 280000,
    currency: 'ARS',
    address: 'Belgrano 560',
    city: 'Santa Rosa',
    province: 'La Pampa',
    description: 'Departamento en edificio con ascensor, cocina equipada y balcón con vista. En el piso 4, luminoso y bien ventilado.',
    features: {
      bedrooms: 2,
      bathrooms: 1,
      coveredArea: 55,
      amenities: ['Ascensor', 'Balcón', 'Cocina equipada', 'Portero eléctrico'],
    },
    images: [
      { asset: { url: 'https://picsum.photos/id/1080/1200/800' } },
      { asset: { url: 'https://picsum.photos/id/1043/1200/800' } },
    ],
    isFeatured: false,
    status: 'disponible',
    publishedAt: '2024-01-28',
  },
];
