import { defineField, defineType } from 'sanity';

export const property = defineType({
  name: 'property',
  title: 'Propiedad',
  type: 'document',
  fields: [
    defineField({ name: 'title', title: 'Título', type: 'string', validation: (r) => r.required() }),
    defineField({
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      options: { source: 'title', maxLength: 96 },
      validation: (r) => r.required(),
    }),
    defineField({
      name: 'status',
      title: 'Estado',
      type: 'string',
      options: { list: ['disponible', 'reservado', 'vendido'], layout: 'radio' },
      initialValue: 'disponible',
      validation: (r) => r.required(),
    }),
    defineField({
      name: 'operation',
      title: 'Operación',
      type: 'string',
      options: { list: [{ title: 'Venta', value: 'venta' }, { title: 'Alquiler', value: 'alquiler' }], layout: 'radio' },
      validation: (r) => r.required(),
    }),
    defineField({
      name: 'propertyType',
      title: 'Tipo de propiedad',
      type: 'string',
      options: {
        list: [
          { title: 'Casa', value: 'casa' },
          { title: 'Departamento', value: 'departamento' },
          { title: 'PH', value: 'ph' },
          { title: 'Terreno', value: 'terreno' },
          { title: 'Local', value: 'local' },
          { title: 'Otro', value: 'otro' },
        ],
      },
      validation: (r) => r.required(),
    }),
    defineField({ name: 'priceOnRequest', title: 'Precio a consultar', type: 'boolean', initialValue: false }),
    defineField({ name: 'price', title: 'Precio', type: 'number' }),
    defineField({ name: 'priceNotes', title: 'Notas de precio', type: 'string', description: 'Ej: + impuestos municipales. Ajuste trimestral con IPC.' }),
    defineField({
      name: 'currency',
      title: 'Moneda',
      type: 'string',
      options: { list: ['USD', 'ARS'], layout: 'radio' },
      initialValue: 'USD',
    }),
    defineField({ name: 'address', title: 'Dirección', type: 'string', validation: (r) => r.required() }),
    defineField({ name: 'city', title: 'Ciudad', type: 'string', initialValue: 'Santa Rosa', validation: (r) => r.required() }),
    defineField({ name: 'province', title: 'Provincia', type: 'string', initialValue: 'La Pampa' }),
    defineField({ name: 'description', title: 'Descripción', type: 'text', rows: 5 }),
    defineField({
      name: 'features',
      title: 'Características',
      type: 'object',
      fields: [
        defineField({ name: 'bedrooms', title: 'Dormitorios', type: 'number' }),
        defineField({ name: 'bathrooms', title: 'Baños', type: 'number' }),
        defineField({ name: 'coveredArea', title: 'Superficie cubierta (m²)', type: 'number' }),
        defineField({ name: 'totalArea', title: 'Superficie total (m²)', type: 'number' }),
        defineField({ name: 'garage', title: 'Cochera', type: 'boolean', initialValue: false }),
        defineField({ name: 'pool', title: 'Pileta', type: 'boolean', initialValue: false }),
        defineField({ name: 'garden', title: 'Jardín', type: 'boolean', initialValue: false }),
        defineField({ name: 'amenities', title: 'Amenities / extras', type: 'array', of: [{ type: 'string' }] }),
      ],
    }),
    defineField({
      name: 'images',
      title: 'Fotos',
      type: 'array',
      of: [{ type: 'image', options: { hotspot: true }, fields: [defineField({ name: 'alt', title: 'Texto alternativo', type: 'string' })] }],
    }),
    defineField({
      name: 'videos',
      title: 'Videos',
      type: 'array',
      of: [{ type: 'file', options: { accept: 'video/*' } }],
    }),
    defineField({ name: 'isFeatured', title: 'Destacada', type: 'boolean', initialValue: false }),
    defineField({ name: 'publishedAt', title: 'Fecha de publicación', type: 'datetime', initialValue: () => new Date().toISOString() }),
  ],
  preview: {
    select: { title: 'title', subtitle: 'address', media: 'images.0' },
  },
});
